import { type FC } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Providers } from '@/lib';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title:       'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout: FC<{ children: React.ReactNode }> = ({ children }) => {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );

};

export default RootLayout;
